sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: O6BoxMKPWMYaPn1IvZ2ERzChU1i78MyciAhgDy2u6hBlIZsIji/9ekE4xIRwUbnImbCEYcqGMkRNplFgHvgntKPdBAlv7Vsh4COrF9QG4dNbj/ORU0osXFfZ5QjAPUv4fVw5CEV+4JAWOxsghTzHFedR8S1YhjFKvE95BlfEdsNEVySXEdzgGisgxz33A2BbhPfibRwdLrKvnkVkyvmNlk8dWmMzEZpZQRIVTUG+NNLM5I0SwGSQ94XibalUYioK/RDj50H1/MTv4griQxKUBgi2BcnmAxTP6Dn12mP9En1dywniYJ255KtHyMyQYZlFY0OKQZ2d9AIPsl3fQN28vyTNiX6VulgRCwYTrlcSPVy9tGri1c6YpjX6Jiu9iODPWeSyLq0olEtblHaPZFGOX0csB7fkIta5yJOKzfsBYAno/CFC2BN+CM9h4gSdgiSx7ZDH/4tcI15YIGpvyrcP18vIcsB2RmQZr2K+jg10AHM/MsKjhWIYItIrf5L6OKAXHu6ZjzOTFKPOyrrjuzHyEmjlcQRpF+eZh2w+slrznteuaA8Jc24IDETaEPf5j8PxO2qbDL4i3u1nG1DibOZn4gfzfjcoqnzFADL3JiR/Z6Ml3uOvp1JSdnGpXStWLNQQuOlgZ6zdC52uP8kTyivL4p7y00BTXIe/xkvBcoT1eMo=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Book-of-Good-Manners-a-Guide-to-Polite-Usage-for-All-Social-Functions_5255
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy